# Generated by Django 6.0.7 on 2026-08-21 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='processing_error',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='policy',
            name='status',
            field=models.CharField(choices=[('processing', 'Processing'), ('ready', 'Ready'), ('failed', 'Failed'), ('queued', 'Queued')], default='queued', max_length=20),
        ),
    ]
