# Generated by Django 6.0.7 on 2026-08-21 05:24

import django.core.validators
import policies.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0002_policy_processing_error_alter_policy_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policy',
            name='file',
            field=models.FileField(upload_to='policies/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'docx', 'doc']), policies.models.validate_file_size]),
        ),
    ]
