# Generated by Django 6.0.7 on 2026-08-25 10:33

import django.core.validators
import policies.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0003_alter_policy_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='policy',
            name='processing_error',
        ),
        migrations.AddField(
            model_name='policy',
            name='processing_error_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='policy',
            name='file',
            field=models.FileField(upload_to='policies/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf']), policies.models.validate_file_size]),
        ),
    ]
