# Generated by Django 6.0.7 on 2026-10-09 17:38

import django.core.validators
import policies.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0004_remove_policy_processing_error_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='page_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='policy',
            name='file',
            field=models.FileField(upload_to='policies/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf']), policies.models.validate_file_size, policies.models.validate_file_is_pdf]),
        ),
    ]
